import { requireRole } from '@/lib/auth';
import AdminShortCoursesClient, { AdminCourseItem } from './AdminShortCoursesClient';

export const dynamic = 'force-dynamic';

export default async function AdminShortCoursesPage() {
  await requireRole(['ADMIN', 'EDU_EXPERT']);

  const initialCourses: AdminCourseItem[] = [
    {
      id: 1,
      code: 'BOOT-AI-101',
      title: 'بوت‌کمپ جامع برنامه‌نویسی پایتون و هوش مصنوعی کاربردی',
      titleEn: 'Comprehensive Python & Applied AI Bootcamp',
      category: 'مهندسی و هوش مصنوعی',
      hours: 60,
      tuitionPrice: 3800000,
      capacity: 35,
      instructorName: 'دکتر محمدرضا جلالی',
      status: 'OPEN',
      learners: [
        {
          id: 101,
          fullName: 'امیررضا صادقی‌راد',
          fullNameEn: 'Amir Reza Sadeghi Rad',
          nationalId: '0021984589',
          mobile: '09121112233',
          courseId: 1,
          amountPaid: 3800000,
          attendanceCount: 10,
          totalSessions: 10,
          finalGrade: 19.5,
          isPassed: true,
          certificateIssued: true,
          certificateNumber: 'AFQ-CERT-2026-9041',
          registeredAt: '۱۴۰۵/۰۸/۱۰',
        },
        {
          id: 102,
          fullName: 'فاطمه موسوی',
          fullNameEn: 'Fatemeh Mousavi',
          nationalId: '0019847120',
          mobile: '09123334455',
          courseId: 1,
          amountPaid: 2660000,
          discountCode: 'AFAGH30',
          attendanceCount: 9,
          totalSessions: 10,
          finalGrade: 17.0,
          isPassed: true,
          certificateIssued: false,
          registeredAt: '۱۴۰۵/۰۸/۱۲',
        },
        {
          id: 103,
          fullName: 'حسین مرادی',
          fullNameEn: 'Hossein Moradi',
          nationalId: '0034567891',
          mobile: '09351234567',
          courseId: 1,
          amountPaid: 3800000,
          attendanceCount: 6,
          totalSessions: 10,
          finalGrade: 9.5,
          isPassed: false,
          certificateIssued: false,
          registeredAt: '۱۴۰۵/۰۸/۱۴',
        },
      ],
    },
    {
      id: 2,
      code: 'BOOT-WEB-202',
      title: 'بوت‌کمپ فول‌استک وب (Next.js 14, React & PostgreSQL)',
      titleEn: 'Full-Stack Web Development Bootcamp',
      category: 'برنامه‌نویسی و وب',
      hours: 80,
      tuitionPrice: 4500000,
      capacity: 30,
      instructorName: 'مهندس سامان افشار',
      status: 'OPEN',
      learners: [
        {
          id: 201,
          fullName: 'مهسا کاظمی‌تبار',
          fullNameEn: 'Mahsa Kazemi Tabar',
          nationalId: '2750191230',
          mobile: '09144445566',
          courseId: 2,
          amountPaid: 4500000,
          attendanceCount: 12,
          totalSessions: 12,
          finalGrade: 18.0,
          isPassed: true,
          certificateIssued: true,
          certificateNumber: 'AFQ-CERT-2026-8812',
          registeredAt: '۱۴۰۵/۰۸/۱۸',
        },
        {
          id: 202,
          fullName: 'سینا پاشایی',
          fullNameEn: 'Sina Pashaei',
          nationalId: '2748912340',
          mobile: '09145556677',
          courseId: 2,
          amountPaid: 3600000,
          discountCode: 'NOROOZ',
          attendanceCount: 11,
          totalSessions: 12,
          finalGrade: 15.5,
          isPassed: true,
          certificateIssued: false,
          registeredAt: '۱۴۰۵/۰۸/۱۹',
        },
      ],
    },
  ];

  return <AdminShortCoursesClient initialCourses={initialCourses} />;
}
